### ISSUE TITLE
العرض التلقائي لملف معين

### ISSUE THREAD

**Issue by ms2052001** [aboueleyes/note-taking#4]
<div dir=rtl>

اقترح إتاحة العرض التلقائي (auto preview) بإيجاد طريقة ما لذلك. وأن نجل ملف الـ Makefile لبناء كل الملفات دفعة واحدة، وأيضا جعل البناء يعمل غير متزامن async بـ concurrency 4 مثلا.

<div>

**Comment by ms2052001** [comment]
<div dir=rtl>

يمكننا بالبناء لا تزامنيا من خلال:

<div dir=ltr>

```sh
❯ make -j4  # 4 parallel processing
❯ make --jobs=4
```

</div>

</div>

**Comment by aboueleyes** [comment]
This depends on the workflow I guess, I am using zathrua as a PDF viewer, and vi to write markdown, vim has a builtin make function so once you will run make, zathrua will update automatically.

**Comment by aboueleyes** [comment]
make (by default) compiles all the files.

**Comment by aboueleyes** [comment]
[https://dev.to/l04db4l4nc3r/vim-to-the-rescue-pdf-preview-2e10](I recommend reading this.)

**Comment by ms2052001** [comment]
Fixed in #5.
